[project]
name = "endgame-mcp-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.16",
    "google-genai>=1.11.0",
    "mcp[cli]>=1.6.0",
]
